const INITIATE_CLOSE = 'INITIATE_CLOSE';
const INITIATE_CLICK = 'INITIATE_CLICK';
const UPDATE_PLACE = 'UPDATE_PLACE';
const CLOSE_DETAIL = 'CLOSE_DETAIL';

export {
  INITIATE_CLOSE,
  INITIATE_CLICK,
  UPDATE_PLACE,
  CLOSE_DETAIL,
};
