const INITIATE_CLOSE = 'INITIATE_CLOSE';
const INITIATE_CLICK = 'INITIATE_CLICK';
const UPDATE_PLACE = 'UPDATE_PLACE';
const CLOSE_DETAIL = 'CLOSE_DETAIL';
const ADD_PLACES_TO_STATE = 'ADD_PLACES_TO_STATE';
const HANDLE_PLACES = 'HANDLE_PLACES';
const GET_NIGERIAN_STATES = 'GET_NIGERIAN_STATES';

export {
  INITIATE_CLOSE,
  INITIATE_CLICK,
  UPDATE_PLACE,
  CLOSE_DETAIL,
  ADD_PLACES_TO_STATE,
  HANDLE_PLACES,
  GET_NIGERIAN_STATES,
};
